spring.application.name=h4j

spring.data.redis.host=plate-brother-steady-90701.db.redis.io
spring.data.redis.port=19368
spring.data.redis.username=default
spring.data.redis.password=
spring.data.redis.database=0
